1- Adding missing parameters to the "ant" command, so it successfully compiles the solution, from now on there should be an ANT_HOME variable pointing to your ant directory in your filesystem, as well as CATALINA_HOME env variable pointing to your Tomcat installation folder. The added parameters are: ant -Dj2ee.server.home="%CATALINA_HOME%" -Dlibs.CopyLibs.classpath=%ANT_HOME%/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar
2- Now the 1_cleanAndBuildAll.bat script automatically copies jWebSocketServer-Bundle-1.0.jar to the CATALINA_HOME\lib folder automatically if we run this script as administrator, otherwise, if this file is missing the following message appears:
"ERROR: jWebSocketServer-Bundle-1.0.jar is missing from your CATALINA_HOME\lib folder. This may cause compilation errors because of missing dependencies for jWebSocketWebAppDemo. You can either run the script 1_cleanAndBuildAll.bat once again as administrator, or just copy the required file jWebSocketServer-Bundle-%JWEBSOCKET_VER%.jar to CATALINA_HOME\lib by yourself."

FYI: At the first run of this script I got a success compilation for all our projects, including the jWebSocketWebAppDemo project.
Thanks,
Victor